version: 3
workdir: .
allow:
  ignoreNotFoundComponents: true

components:
  cmd:
    in:
      - cmd/**
  cli:
    in:
      - internal/cli/**
  config:
    in:
      - internal/config/**
  rules:
    in:
      - internal/rules/**
  scan:
    in:
      - internal/scan/**
  baseline:
    in:
      - internal/baseline/**
  ignore:
    in:
      - internal/ignore/**
  io:
    in:
      - internal/io/**
  output:
    in:
      - internal/output/**

commonComponents:
  - config
  - rules
  - io

deps:
  cmd:
    anyProjectDeps: true
  cli:
    anyProjectDeps: true
  scan:
    mayDependOn:
      - rules
      - io
      - ignore
    anyVendorDeps: true
  baseline:
    mayDependOn:
      - scan
    anyVendorDeps: false
  ignore:
    anyProjectDeps: true
    anyVendorDeps: true
  output:
    mayDependOn:
      - rules
      - scan
    anyVendorDeps: true
  config:
    mayDependOn:
      - rules
    anyVendorDeps: true
  rules:
    anyProjectDeps: true
    anyVendorDeps: false
  io:
    anyProjectDeps: true
    anyVendorDeps: false
