version: "2"

run:
  timeout: 5m
  tests: true

output:
  sort-results: true

# linters-settings:
#   depguard:
#     rules:
#       main:
#         list-mode: lax
#         deny:
#           - pkg: "io/ioutil"
#             desc: "deprecated; use io or os"
#           - pkg: "github.com/pkg/errors"
#             desc: "use standard errors"
#           - pkg: "golang.org/x/net/context"
#             desc: "use context"
#   gocyclo:
#     min-complexity: 15
#   govet:
#     enable-all: true
#     disable:
#       - fieldalignment
#   lll:
#     line-length: 120
#     tab-width: 2
#   revive:
#     rules:
#       - name: exported
#       - name: indent-error-flow
#       - name: if-return
#       - name: range
#       - name: var-declaration
#       - name: var-naming
#         arguments:
#           - ["ID", "JSON", "SARIF", "YAML", "CLI", "HTTP", "URL"]
#   errcheck:
    exclude-functions:
      - (*os.File).Close

linters:
  default: fast
  enable:
    - bodyclose
    - depguard
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nilerr
    - nilnil
    - noctx
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - gosec

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: false
